# SNMP v1/v2c community string "public" (vulnérable)
rocommunity public default
rocommunity public 192.168.30.0/24

# System info — sera overridé par start.sh
syslocation "Office Floor 2"
syscontact  "IT Support <it@corp.local>"

# Printer MIB values simulés
agentaddress udp:161,tcp:161

# Allow all
view all included .1
access notConfigGroup "" any noauth exact all none none
