listen=YES
listen_ipv6=NO
anonymous_enable=YES
local_enable=YES
write_enable=YES
anon_upload_enable=YES
anon_mkdir_write_enable=YES
dirmessage_enable=YES
xferlog_enable=YES
connect_from_port_20=YES
xferlog_std_format=YES
ftpd_banner=220 Welcome to FTP Service
chroot_local_user=NO
allow_writeable_chroot=YES
secure_chroot_dir=/var/empty
pasv_enable=YES
pasv_min_port=30000
pasv_max_port=30010
anon_root=/var/ftp
