server {
    listen 80;
    listen 8080;
    server_name _;
    root /var/www/html;
    index index.html;

    add_header X-Frame-Options SAMEORIGIN;

    location / {
        try_files $uri $uri/ =404;
    }

    location /ISAPI/ {
        return 401 '{"statusCode":401,"statusString":"Unauthorized"}';
        add_header Content-Type application/json;
    }

    location /cgi-bin/ {
        return 200 'OK';
    }
}
